import type { CarAgent, CityMap } from "../types";

export const city: CityMap = {
  nodes: [
    { id: "n1", position: { x: -72, z: -48 } },
    { id: "n2", position: { x: -24, z: -48 }, control: "stop" },
    { id: "n3", position: { x: 24, z: -48 } },
    { id: "n4", position: { x: 72, z: -48 }, control: "traffic-light" },
    { id: "n5", position: { x: -72, z: 0 }, control: "traffic-light" },
    { id: "n6", position: { x: -24, z: 0 } },
    { id: "n7", position: { x: 24, z: 0 }, control: "stop" },
    { id: "n8", position: { x: 72, z: 0 } },
    { id: "n9", position: { x: -72, z: 48 } },
    { id: "n10", position: { x: -24, z: 48 }, control: "stop" },
    { id: "n11", position: { x: 24, z: 48 }, control: "traffic-light" },
    { id: "n12", position: { x: 72, z: 48 } },
  ],
  edges: [
    { id: "e1", from: "n1", to: "n2", speedLimit: 11 },
    { id: "e2", from: "n2", to: "n3", speedLimit: 11 },
    { id: "e3", from: "n3", to: "n4", speedLimit: 11, oneWay: true },
    { id: "e4", from: "n5", to: "n6", speedLimit: 9 },
    { id: "e5", from: "n6", to: "n7", speedLimit: 9 },
    { id: "e6", from: "n7", to: "n8", speedLimit: 9 },
    { id: "e7", from: "n9", to: "n10", speedLimit: 10 },
    { id: "e8", from: "n10", to: "n11", speedLimit: 10 },
    { id: "e9", from: "n11", to: "n12", speedLimit: 10 },
    { id: "e10", from: "n1", to: "n5", speedLimit: 8 },
    { id: "e11", from: "n5", to: "n9", speedLimit: 8, oneWay: true },
    { id: "e12", from: "n2", to: "n6", speedLimit: 8 },
    { id: "e13", from: "n6", to: "n10", speedLimit: 8 },
    { id: "e14", from: "n3", to: "n7", speedLimit: 8 },
    { id: "e15", from: "n7", to: "n11", speedLimit: 8 },
    { id: "e16", from: "n4", to: "n8", speedLimit: 8 },
    { id: "e17", from: "n8", to: "n12", speedLimit: 8 },
  ],
  buildings: [
    {
      id: "b1",
      name: "Civic Center",
      position: { x: -48, z: -24 },
      size: { x: 22, z: 18 },
      height: 18,
      kind: "civic",
    },
    {
      id: "b2",
      name: "Market Hall",
      position: { x: 0, z: -22 },
      size: { x: 20, z: 20 },
      height: 12,
      kind: "retail",
    },
    {
      id: "b3",
      name: "North Offices",
      position: { x: 48, z: -22 },
      size: { x: 24, z: 18 },
      height: 24,
      kind: "office",
    },
    {
      id: "b4",
      name: "Canal Lofts",
      position: { x: -48, z: 24 },
      size: { x: 22, z: 20 },
      height: 16,
      kind: "residential",
    },
    {
      id: "b5",
      name: "Clinic",
      position: { x: 0, z: 24 },
      size: { x: 20, z: 18 },
      height: 14,
      kind: "civic",
    },
    {
      id: "b6",
      name: "Station Shops",
      position: { x: 48, z: 24 },
      size: { x: 24, z: 20 },
      height: 13,
      kind: "retail",
    },
  ],
  destinations: [
    {
      id: "civic",
      name: "Civic Center",
      nodeId: "n2",
      position: { x: -48, z: -24 },
      demand: 0.55,
    },
    {
      id: "market",
      name: "Market Hall",
      nodeId: "n7",
      position: { x: 0, z: -22 },
      demand: 0.75,
    },
    {
      id: "station",
      name: "Station Shops",
      nodeId: "n11",
      position: { x: 48, z: 24 },
      demand: 0.85,
    },
  ],
  parkingSpots: [
    {
      id: "p1",
      nodeId: "n2",
      position: { x: -32, z: -58 },
      price: 4,
      baseAvailability: 0.65,
      occupancyRisk: 0.35,
      legal: true,
      accessible: true,
    },
    {
      id: "p2",
      nodeId: "n6",
      position: { x: -12, z: -10 },
      price: 8,
      baseAvailability: 0.45,
      occupancyRisk: 0.58,
      legal: true,
      accessible: true,
    },
    {
      id: "p3",
      nodeId: "n7",
      position: { x: 36, z: 10 },
      price: 11,
      baseAvailability: 0.35,
      occupancyRisk: 0.72,
      legal: true,
      accessible: true,
    },
    {
      id: "p4",
      nodeId: "n10",
      position: { x: -12, z: 58 },
      price: 3,
      baseAvailability: 0.82,
      occupancyRisk: 0.2,
      legal: true,
      accessible: false,
    },
    {
      id: "p5",
      nodeId: "n11",
      position: { x: 36, z: 58 },
      price: 6,
      baseAvailability: 0.75,
      occupancyRisk: 0.28,
      legal: true,
      accessible: true,
    },
    {
      id: "p6",
      nodeId: "n4",
      position: { x: 58, z: -58 },
      price: 0,
      baseAvailability: 1,
      occupancyRisk: 0.05,
      legal: false,
      accessible: true,
    },
  ],
};

export const initialCars: CarAgent[] = [
  {
    id: "car-1",
    color: "#3b82f6",
    position: { ...city.nodes[0].position },
    currentNodeId: "n1",
    destinationId: "market",
    path: ["n1", "n2", "n6", "n7"],
    pathIndex: 0,
    state: "driving",
    speed: 13,
  },
  {
    id: "car-2",
    color: "#ef4444",
    position: { ...city.nodes[8].position },
    currentNodeId: "n9",
    destinationId: "station",
    path: ["n9", "n10", "n11"],
    pathIndex: 0,
    state: "driving",
    speed: 11,
  },
  {
    id: "car-3",
    color: "#14b8a6",
    position: { ...city.nodes[3].position },
    currentNodeId: "n4",
    destinationId: "civic",
    path: ["n4", "n8", "n7", "n6", "n2"],
    pathIndex: 0,
    state: "driving",
    speed: 10,
  },
];

